"""empty message

Revision ID: 215b39a98fc2
Revises: 927d8a75d6c1
Create Date: 2016-02-01 08:43:16.062087

"""

# revision identifiers, used by Alembic.
revision = '215b39a98fc2'
down_revision = '927d8a75d6c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('subhead', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('headline')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
