"""empty message

Revision ID: 79b2b82bf6d8
Revises: 215b39a98fc2
Create Date: 2016-02-01 08:47:43.861586

"""

# revision identifiers, used by Alembic.
revision = '79b2b82bf6d8'
down_revision = '215b39a98fc2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    ### end Alembic commands ###
